name: Docker Image CI dev

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./home-soft-backend  

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose up --build --force-rm --no-cache
      working-directory: ${{env.working-directory}}
